@startuml Operazione 2a.1
skinparam Style strictuml

title 2a.1 deleteExtraDuty

collections UI

participant "kitchenTMgr: KitchenTaskManager" as ktm
UI -> ktm: deleteExtraDuty(kitchenDuty)
activate ktm

alt currentSheet==null
    UI <<-- ktm: throw UseCaseLogicException
else
    participant "kitchenTMgr.currentSheet: SummarySheet" as ss
    ktm -> ss: deleteExtraDuty(kitchenDuty)
    activate ss

    loop ""for all"" task ""in"" currentSheet.tasks
        alt task.optionalDuty && (task.duty == kitchenDuty)
            loop ""for all"" job ""in"" task.jobs
                participant "task.jobs: ArrayList<Job>" as j
                participant "job.turn: KitchenTurn" as jobKitchenTurn

                ss -> jobKitchenTurn: freeTime(job.cook, job.estimatedDuration)
                note left: La definizione completa di\n//freeTime()// è nel DSD 6c
                activate jobKitchenTurn
                deactivate jobKitchenTurn

                ss -> j: remove(job)
                activate j
                deactivate j
            end

            participant "currentSheet.tasks: ArrayList<Task>" as tasks
            ss -> tasks: remove(task)
            activate tasks
            deactivate tasks
        end
    end
    
    participant "currentSheet.extraDuties: ArrayList<KitchenDuty>" as kdList
    ss -> kdList: remove(kitchenDuty)
    activate kdList
    deactivate kdList
    
    ktm <<-- ss: task
    deactivate ss

    participant "ktr: KitchenTaskEventReceiver" as ktr
    |||
    ktm -> ktm: notifyDeleteExtraDuty(kitchenDuty, task)
        activate ktm
    loop ""for all"" ktr ""in"" eventReceivers
        ktm -> ktr : updateDeleteExtraDuty(kitchenDuty, task)
        activate ktr
        deactivate ktr
    end
    deactivate ktm

    UI <<-- ktm : currentSheet
    deactivate ktm

    
end

@enduml