@startuml Operazione 5
skinparam Style strictuml

collections UI

participant "taskManager: KitchenTaskManager" as tm
participant "ktr: KitchenTaskEventReceiver" as ktr

UI -> tm: editTask(newAmount?, newDuration?, newToDo?)
activate tm

participant "task: Task" as task

alt currentSheet==null
    UI <<-- tm: throw UseCaseLogicException
else
    tm -> task: editDetails(newAmount?, newDuration?, newToDo?)
    activate task

    alt newAmount != null
        task -> task: this.amount = newAmount
    end

    alt newDuration != null
        task -> task: this.duration = Duration.ofSeconds(newDuration)
    end

    alt newToDo != null
        alt this.jobs.count() > 0
            tm <<-- task: throw UseCaseLogicException
            UI <<-- tm: throw UseCaseLogicException
        end

        task -> task: this.toDo = newToDo
    end

    tm <<--task: task
    deactivate task
    |||
    tm -> tm: notifyEditTask(task)
    activate tm
    loop ""for all"" ktr ""in"" eventReceivers
        tm -> ktr : updateEditTask(task)
        activate ktr
        deactivate ktr
    end
    deactivate tm

    UI <<-- tm: task
    deactivate tm

end
@enduml