@startuml Operazione 6a
skinparam Style strictuml

collections UI

'commento di prova per vedere se riesco a pushare sul nuovo pc

participant "taskManager: KitchenTaskManager" as tm
participant "task: Task" as task
participant "ktr: KitchenTaskEventReceiver" as ktr
participant "job.turn: KitchenTurn" as t
participant "task.jobs: ArrayList<KitchenJob>" as jl

UI -> tm: deleteKitchenJob(task, job)
activate tm

alt !task.jobs.contains(job)
    UI <<-- tm: throw TaskException
else
    tm -> task: deleteKitchenJob(job)
    activate task
    task -> t: freeTime(job.cook, job.estimatedDuration)
    activate t
    return turn

    task -> jl: remove(job)
    activate jl
    deactivate jl


    deactivate task

    |||
    tm -> tm: notifyDeletedKitchenJob(job)
    activate tm
    loop ""for all"" ktr ""in"" eventReceivers
        tm -> ktr : updateDeletedKitchenJob(job)
        activate ktr
        deactivate ktr
    end
    deactivate tm

    UI <<-- tm: task
    deactivate tm

end

deactivate tm

@enduml