@startuml Operazione 2
skinparam Style strictuml

collections UI

participant "kitchenTMgr: KitchenTaskManager" as ktm
UI -> ktm: addExtraDuty(kitchenDuty)
participant "ktr: KitchenTaskEventReceiver" as ktr

activate ktm

alt currentSheet==null
    UI <<-- ktm: throw UseCaseLogicException
else
    participant "kitchenTMgr.currentSheet: SummarySheet" as ss
    ktm -> ss: addExtraDuty(kitchenDuty)
    activate ss

    participant "currentSheet.extraDuties: ArrayList<KitchenDuty>" as kdList
    ss -> kdList: add(kitchenDuty)
    activate kdList
    deactivate kdList

    participant "task: Task" as t
    ss -->> t**: create(kitchenDuty, true)
    activate t
    t -> t: this.amount = 0
    t -> t: this.estimatedDuration = 0
    t -> t: this.toDo = true
    t -> t: this.optionalDuty = true
    t -> t: this.duty = kitchenDuty
    ss <<-- t:task
    deactivate t
    
    participant "currentSheet.tasks: ArrayList<Task>" as tasks
    ss -> tasks: add(task)

    activate tasks
    deactivate tasks

    ktm <<-- ss: task
    deactivate ss
    |||
    ktm -> ktm: notifyAddExtraDuty(kitchenDuty, task)
    activate ktm
    loop ""for all"" ktr ""in"" eventReceivers
        ktm -> ktr : updateAddExtraDuty(kitchenDuty. task)
        activate ktr
        deactivate ktr
    end
    deactivate ktm

    UI <<-- ktm : task
    deactivate ktm

    
end

@enduml