@startuml Operazione 3
skinparam Style strictuml

collections UI

participant "kitchenTMgr: KitchenTaskManager" as ktm
UI -> ktm: sortTask(task, position)
activate ktm

alt currentSheet==null 
    UI <<-- ktm: throw UseCaseLogicException
else
    participant "kitchenTMgr.currentSheet: SummarySheet" as ss
    
    ktm -> ss: sortTask(task, position)
    activate ss
    participant "currentSheet.tasks: ArrayList<task>" as t
    
    alt currentSheet.tasks.contains(task) && position >= 0
        ss -> t: remove(task)
        activate t
        deactivate t
        ss -> t: add(position,task)
        activate t
        deactivate t
    end
    
    ktm <<-- ss: currentSheet
    deactivate ss
    UI <<-- ktm : currentSheet
    deactivate ktm
end

@enduml