@startuml Operazione 6
skinparam Style strictuml

collections UI

participant "taskManager: KitchenTaskManager" as tm
UI -> tm: createJob(task, turn, amount, estimatedDuration)
activate tm

participant "task: Task" as task
participant "ktr: KitchenTaskReceiver" as ktr

alt currentSheet == null || Date.now() > turn.endDate || turn.complete
    UI <<-- tm: throw UseCaseLogicException
else task.amount < 0 || task.estimatedDuration < 0
    UI <<-- tm: throw TaskException
else

    tm -> task: addJob(turn, amount, estimatedDuration)
    activate task

    participant "job: Job" as job
    task -->> job**: create(turn, amount, estimatedDuration)

    activate job
        job -> job: this.amount = amount
        job -> job: this.duration = estimatedDuration
        job -> job: this.turn = turn
        job -> job: this.cook = null

    return job

    tm <- task: job
    deactivate task

    loop for all ktr in eventReceivers
        tm -> ktr : updateCreateJob(job)
        activate ktr
        deactivate ktr
    end

    UI <- tm: job
    deactivate tm
    
end

@enduml