@startuml
skinparam Style strictuml
skinparam classAttributeIconSize 0
skinparam linetype polyline
skinparam linetype ortho

title DOM


object Sezione{
    nome: testo
}
object Menù{
    titolo: testo
    pubblicato: sì/no
    richiede cuoco: sì/no
    piatti caldi: sì/no
    richiede cucina: sì/no
    buffet: sì/no
    finger food: sì/no
    approvato: sì/no
}
object Voce{
    descrizione: testo
}
object Ricetta
object Preparazione
object "Mansione di Cucina" as Mansione{
    nome: testo
    autore: testo
    istruzioni: testo
    quantità risultante: numero
    TAC: numero
    TT: numero
    TU: numero
}
object Evento{
    durata evento: numero
    numero partecipanti: numero
    luogo
}
object Servizio{
    giorno: Data
    orario: range ore
    tipologia: testo
}
object "Foglio Riepilogativo" as Foglio
object Ricettario
object Chef
object Compito{
    quantità: numero
    tempo stimato: numero
}
object Incarico
object "Incarico di Cucina" as IncaricoCucina{
    quantità: numero
    tempo stimato: numero
    completato: sì/no
}
object "Incarico di Servizio" as IncaricoServizio{
    ruolo: testo
}

object "Turno di Cucina" as TurnoCucina
object "Turno di Servizio" as TurnoServizio
object Turno{
    giorno: Data
    orario: range ore
}
object Cuoco
object "Personale di Servizio" as PersonaleServizio
object Personale
object Organizzatore
object Proposta
object "Proposta di Aggiunta" as PropostaAggiunta
object "Proposta di Rimozione" as PropostaRimozione


Menù "1" *-- "0..n" Sezione: contiene
Menù "0..1" *-- "0..n" Voce: appartiene
Menù "0..1" - "0..n" Servizio: è scelto per
Menù "0..n" -- "0..n" Evento: /in uso in
Mansione "1" -- "0..n" Compito : programmata in
Mansione "0..n" -- "0..n" Menù : / è inclusa in
Mansione "0..n" *-- "1" Ricettario: si trova in
Voce "0..n" -- "1" Ricetta: fa riferimento a
Voce "0..n" *-- "0..1" Sezione: appartiene
Preparazione "0..n" -- "0..n" Ricetta: fa parte di
Preparazione --|> Mansione
Ricetta --|> Mansione
PropostaAggiunta --|> Proposta
PropostaRimozione --|> Proposta
PropostaAggiunta "0..n" -- "1" Mansione: aggiunge
PropostaRimozione "0..n" -- "1" Voce: rimuove
Proposta "0..n" -- "1" Servizio: modifica
Evento "1" -- "1..n" Servizio: è suddiviso in
Evento "0..n" -- "0..1" Chef: assegnato a
Servizio "1" -- "0..1" Foglio: ha associato
Foglio "1" *-- "1..n" Compito: organizza
Foglio "0..n" -- "0..n" Mansione: comprende
Compito "1" *-- "0..n" Incarico: è distribuito su
Incarico "0..n" -- "1" Turno: assegnato in
Cuoco "0..1" -- "0..n" Incarico: incaricato di
Cuoco "0..n" -- "0..n" Turno: si rende disponibile in
IncaricoCucina --|> Incarico
IncaricoServizio --|> Incarico
PersonaleServizio "0..n" -- "0..n" TurnoServizio: si rende disponibile in
TurnoServizio -|> Turno
TurnoCucina -|> Turno
Cuoco -|> Personale
PersonaleServizio --|> Personale
Personale "1..n" -- "0..n" Servizio: deciso per
Organizzatore "0..1" -- "0..n" Evento: gestisce



@enduml
