@startuml
skinparam Style strictuml
skinparam SequenceMessageAlign center

skinparam sequence {
    ActorBorderColor Black
    ActorBackgroundColor White
    ParticipantBorderColor Black
    ParticipantBackgroundColor White
}

actor Chef
participant Sistema

title Gestire Eventi - UC Base

Chef -> Sistema: **1**. creaEvento(dataInizio, cliente)
return nuovo evento

loop #a3daff
    opt #b6efb6
        Chef -> Sistema: **2**. aggiungiNote(note)
        return ok
        ||10||
    end

    opt #b6efb6
        Chef -> Sistema: **3**. visualizzaStatoCucina()
        return stato cucina
        ||10||
    end

    opt #b6efb6
        Chef -> Sistema: **4**. modificaDettagliEvento(dataInizio?, cliente?)
        return ok
        ||10||
    end

    opt #b6efb6
        Chef -> Sistema: **5**. aggiungiServizio(offsetInizio, rangeOrario, numeroCommensali, luogo, dettagli, strategia)
        return ok
        ||10||
    end

    opt #b6efb6
        Chef -> Sistema: **6**. assegnaChef(chef, strategia)
        return ok
        ||10||
    end

    opt #b6efb6
        Chef -> Sistema: **7**. confermaMenuServizio(servizio)
        return ok
        ||10||
    end

    opt #b6efb6
        Chef -> Sistema: **8**. assegnaPersonale(dipendente, turnoServizio, ruolo?)
        return ok
        ||10||
    end
end
@enduml