@startuml
skinparam Style strictuml
skinparam SequenceMessageAlign center

skinparam sequence {
    ActorBorderColor Black
    ActorBackgroundColor White
    ParticipantBorderColor Black
    ParticipantBackgroundColor White
}

actor Chef
participant Sistema

title Gestire Eventi - Operazione 8

Chef -> Sistema: **1**. creaEvento()
return nuovo evento

loop #e0e0e0
    opt #e0e0e0
        Chef -> Sistema: **2**. aggiungiNote(note)
        return ok
        ||10||
    end

    opt #e0e0e0
        Chef -> Sistema: **3**. visualizzaStatoCucina()
        return stato cucina
        ||10||
    end

    opt #e0e0e0
        Chef -> Sistema: **4**. modificaDettagliEvento(periodicità?)
        return ok
        ||10||
    end

    opt #e0e0e0
        Chef -> Sistema: **5**. aggiungiServizio(data, oraInizio, oraTermine, luogo, dettagli)
        return ok
        ||10||
    end

    opt #e0e0e0
        Chef -> Sistema: **6**. assegnaChef(chef)
        return ok
        ||10||
    end

    opt #e0e0e0
        Chef -> Sistema: **7**. confermaMenu(menu)
        return ok
        ||10||
    end

    opt #b6efb6
        alt #f3d0ff
            Chef -> Sistema: **8**. assegnaPersonale(dipendente, turno, ruolo?)
            alt #f3a7c9
                return ok
            else
                Chef <- Sistema: **8.a.1**. servizio annullato o terminato
                destroy Sistema
                ||10||
            end
            ||10||
        else
            Chef -> Sistema: **8a.1**. rimuoviPersonale(dipendente, turno)
            alt #f3a7c9
                return ok
            else
                Chef <- Sistema: **8a.1a.1**. servizio annullato o terminato
                destroy Sistema
                ||10||
            end
            ||10||
        end
    end
end
@enduml