@startuml
skinparam Style strictuml
skinparam SequenceMessageAlign center

skinparam sequence {
    ActorBorderColor Black
    ActorBackgroundColor White
    ParticipantBorderColor Black
    ParticipantBackgroundColor White
}

actor "Organizzatore" as org
participant Sistema

title Gestire Eventi - Operazione 4

org -> Sistema: **1**. creaEvento(dataInizio, cliente, name)
return nuovo evento

loop #e0e0e0
    opt #e0e0e0
        org -> Sistema: **2**. aggiungiNote(note)
        return ok
        ||10||
    end

    opt #e0e0e0
        org -> Sistema: **3**. visualizzaStatoCucina()
        return stato cucina
        ||10||
    end

    opt #b6efb6
        alt #f3d0ff
            org -> Sistema: **4**. modificaDettagliEvento(dataInizio?, cliente?)
            alt #f3a7c9
                return ok
                ||10||
            else
                org <- Sistema: **4a.1**. lavori avviati: dataInizio non modificabile
                destroy Sistema
                ||10||
             else
                org <- Sistema: **4b.1**. data specificata già passata
                destroy Sistema
                ||10||
            end
        else
            org -> Sistema: **4a.1**. modificaPeriodicità(eventoBase, periodicità, dataPartenza)
            return ok
    end

    opt #e0e0e0
        org -> Sistema: **5**. aggiungiServizio(offsetInizio, rangeOrario, numeroCommensali, luogo, dettagli, strategia)
        return ok
        ||10||
    end

    opt #e0e0e0
        org -> Sistema: **6**. assegnaChef(chef, strategia)
        return ok
        ||10||
    end

    opt #e0e0e0
        org -> Sistema: **7**. confermaMenuServizio(servizio)
        return ok
        ||10||
    end

    opt #e0e0e0
        org -> Sistema: **8**. assegnaPersonale(dipendente, turnoServizio, ruolo?)
        return ok
        ||10||
    end
end
@enduml