@startuml
skinparam Style strictuml
skinparam SequenceMessageAlign center

skinparam sequence {
    ActorBorderColor Black
    ActorBackgroundColor White
    ParticipantBorderColor Black
    ParticipantBackgroundColor White
}

actor Chef
participant Sistema

title Gestire Eventi - Operazione 1

alt #f3d0ff
    Chef -> Sistema: **1**. creaEvento(dataInizio, cliente)
    alt #f3a7c9
        return nuovo evento
        ||10||
    else
        Chef <- Sistema: **1a.1**. data specificata già passata
        destroy Sistema
        ||10||
    end
else
    Chef -> Sistema: **1a.1**. apriEvento(evento)
    alt #f3a7c9
        return foglio evento
        ||10||
    else
        Chef <- Sistema: **1a.1a.1**. evento terminato o annullato
        destroy Sistema
        ||10||
    else
        Chef <- Sistema: **1a.1b.1**. l'organizzatore non gestisce evento
        destroy Sistema
        ||10||
    end

    opt #b6efb6
        alt #f3d0ff
            Chef -> Sistema: **1a.2**. annullaEvento(evento, strategia)
            return warning penale
            destroy Sistema
            ||10||
        else
            Chef -> Sistema: **1a.2a.1**. terminaEvento(evento)
            return ok
            destroy Sistema
            ||10||
        else
            Chef -> Sistema: **1a.2b.1**. eliminaEvento(evento, strategia)
            alt #f3a7c9
                return ok
                destroy Sistema
                ||10||
            else
               Chef <- Sistema: **1a.2b.1a.1**. evento confermato
               destroy Sistema
               ||10||
            end
            ||10||
        end
        ' non abbiamo modo di modificare il colore della X
        ||10||
    end
else
    Chef -> Sistema: **1b.1**. apriEventoTerminatoAnnullato(evento)
    alt #f3a7c9
        return foglio evento
        ||10||
    else
        Chef <- Sistema: **1b.1a.1**. evento non terminato o non annullato
        destroy Sistema
        ||10||
    else
        Chef <- Sistema: **1b.1b.1**. l'organizzatore non gestisce evento
        destroy Sistema
        ||10||
    end

    opt #b6efb6
        Chef -> Sistema: **1b.2**. gestisciNote(note)
        return ok
        ||10||
    end

    ||10||
    destroy Sistema
'    note over Chef, Sistema #fff: Il caso d'uso termina.
    ||10||
end

loop #e0e0e0
    opt #e0e0e0
        Chef -> Sistema: **2**. aggiungiNote(note)
        return ok
    end

    opt #e0e0e0
        Chef -> Sistema: **3**. visualizzaStatoCucina()
        return stato cucina
    end

    opt #e0e0e0
        Chef -> Sistema: **4**. modificaDettagliEvento(periodicità?, dataInizio?)
        return ok
    end

    opt #e0e0e0
        Chef -> Sistema: **5**. aggiungiServizio(offsetInizio, rangeOrario, numeroCommensali, luogo, dettagli)
        return ok
    end

    opt #e0e0e0
        Chef -> Sistema: **6**. assegnaChef(chef)
        return ok
    end

    opt #e0e0e0
        Chef -> Sistema: **7**. confermaMenuServizio(servizio)
        return ok
    end

    opt #e0e0e0
        Chef -> Sistema: **8**. assegnaPersonale(dipendente, turno, ruolo?)
        return ok
    end
end
@enduml