@startuml
skinparam Style strictuml
skinparam SequenceMessageAlign center

skinparam sequence {
    ActorBorderColor Black
    ActorBackgroundColor White
    ParticipantBorderColor Black
    ParticipantBackgroundColor White
}

actor Chef
participant Sistema

title Gestire compiti della Cucina - Operazione 7

Chef -> Sistema: **1**. creaEvento()
return nuovo evento

loop #e0e0e0
    opt #e0e0e0
        Chef -> Sistema: **2**. aggiungiNote(note)
        return ok
        ||10||
    end

    opt #e0e0e0
        Chef -> Sistema: **3**. visualizzaStatoCucina()
        return stato cucina
        ||10||
    end

    opt #e0e0e0
        Chef -> Sistema: **4**. compilaDettagliEvento(durata?, periodicità?, numeroServizi?, numeroPartecipanti?, date?, luoghi?)
        return ok
        ||10||
    end

    opt #e0e0e0
        Chef -> Sistema: **5**. aggiungiServizio(data, oraInizio, oraTermine, tipologia, dettagli)
        return ok
        ||10||
    end

    opt #e0e0e0
        Chef -> Sistema: **6**. assegnaChef(chef)
        return ok
        ||10||
    end

    opt #b6efb6
        alt #f3d0ff
            Chef -> Sistema: **7**. confermaMenu(menu)
            return ok
            ||10||
        else
            Chef -> Sistema: **7a.1**. proponiModificaMenu(menu, modifica)
            return ok
            ||10||
        end
    end

    opt #e0e0e0
        Chef -> Sistema: **8**. assegnaPersonale(personale, turno)
        return ok
        ||10||
    end
end
@enduml